name: 'Takumi Guard setup'
description: 'Configure package registries to route through Takumi Guard'
runs:
  using: 'composite'
  steps:
    - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1
      with:
        bot-id: "BT01KRJ741G9T8KN3Y91SHA5KF1F"
