---
name: Lint Code Base
run-name: 'Lint code base on "${{ github.event.pull_request.title }}" by ${{ github.actor }}'

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  actionlint:
    name: 'Lint: GitHub Actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: github actions lint
        uses: reviewdog/action-actionlint@v1
        with:
          filter_mode: diff_context
          fail_on_error: true
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    name: 'Lint: ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/init-node

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--cache --ext .ts,.tsx,.js,.jsx,.mdx,.vue .'
          github_token: ${{ secrets.GITHUB_TOKEN }}
